/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ILogosTypescriptIconRound: typeof import('~icons/logos/typescript-icon-round')['default']
    ILogosVitejs: typeof import('~icons/logos/vitejs')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./../components/Versions.vue')['default']
  }
}
